apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ zalando_postgresql_cluster_name }}
spec:
  teamId: "{{ zalando_postgresql_teamid }}"
  volume:
    size: 1Gi
    storageClass: {{ zalando_postgresql_storage_class }}
  numberOfInstances: {{ zalando_postgresql_number_instances }}
  users:
{% for user in zalando_postgresql_users %}
    {{ user.name }}:
{% for permission in user.permissions %}
    - {{ permission }}
{% endfor %}
{% endfor %}
  databases:
{% for db in zalando_postgresql_databases %}
    {{ db.name }}: {{ db.owner }}  # dbname: owner
{% endfor %}
  postgresql:
    version: "11"
